name: Test - Daily

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - manual-daily-text
  schedule:
    - cron: "0 9 * * *"

jobs:
  daily-tests:
    name: Daily Tests
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'deepgram/deepgram-python-sdk'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 30
    steps:

      - name: Checkout code by commit
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Config git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch main
          git config --global pull.rebase true
          git config --global url."https://git:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"

      - name: Get dependencies
        shell: bash
        run: |
          make ensure-deps

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run all checks
        shell: bash
        env:
          DEEPGRAM_API_KEY: ${{ secrets.GH_ASR_TESTS_API_KEY_PUBLIC_R }}
        run: |
          make daily-test

      - name: Get dependencies
        shell: bash
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="response-shape-${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"

          # create a PR
          git add ./tests/response_data
          git commit -s -m "auto-generated - update Response Shapes"
          git push origin "$BRANCH_NAME"
          gh pr create --title "auto-generated - update Response Shapes" --body "auto-generated - update Response Shapes" --base "main" --head "$BRANCH_NAME"
          sleep 10
          gh pr merge "$BRANCH_NAME" --delete-branch --squash --admin
