name: Test - Unit

on:
  pull_request:
      types:
        - assigned
        - opened
        - synchronize
        - reopened
jobs:
  build:
    name: Unit Tests
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'deepgram/deepgram-python-sdk'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Checkout code by commit
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run all checks
        shell: bash
        env:
          DEEPGRAM_API_KEY: ${{ secrets.GH_ASR_TESTS_API_KEY_PUBLIC_R }}
        run: |
          make unit-test
